### ISSUE TITLE
Role Selection

### ISSUE THREAD

**Issue by Jurij97** [GreyWolfDev/Werewolf#396] opened 2019-01-04 17:54 UTC
Hi everyone. I post this here because i dont know where else i could post.
May a future project could be permitting admin to  disable any type of characters?

**Comment by Olgabrezel** [comment] 2019-01-05 11:32
We have already tried working on this, the problem is just, how do we guarantee the bot is able to create a balanced game with up to 35 players if many roles are disabled? We couldn't come up with a working solution to that yet, but we're probably going to try again in the future. Gonna leave this issue open as a reminder.

**Comment by Jurij97** [comment] 2019-01-05 11:46
Thank you for the response. 
I tried to modify the source code myself. I see that the definition of the characters is in a switch_case, in werewolfnode->werewolf.cs. I put the characters i dont lin in a comment bracket so the compiler does not see it. I want to try to build a bot with the source code modified but from your message i start to thinking that the bot will no more work with this modifies. 

Just another issue: the way to build the bot is that way explained in the SETUP part?

**Comment by Olgabrezel** [comment] 2019-01-05 11:52
The instructions on cloning the bot in the README.md file are quite outdated. Maybe we can have a look at those as well, but there are currently no full working instructions, sorry.

**Comment by Jurij97** [comment] 2019-01-05 11:55
Thank you very much.

**Comment by Olfi01** [comment] 2019-03-26 09:28
On this note: Role selection is the next point of my werewolf ToDo list, and I will consider putting the readme there as well.

**Comment by Jurij97** [comment] 2019-04-03 05:49
Appreciate it.
Greetings from Italy.

Il mar 26 mar 2019, 10:28 Olfi01 <notifications@github.com> ha scritto:

**Comment by Olgabrezel** [comment] 2019-09-27 18:16
We will hopefully soon merge beta and the role selection will be a thing :D

I'll close this issue now, thanks for the input.

**Closed by Olgabrezel** 2019-09-27 18:16 UTC
Labels: Backlog
